### ISSUE TITLE
Add the slack invitation to the read me

### ISSUE THREAD

**Issue by anjula-sack** [tillioss/tilli-machine-learning#5]
**Is your feature request related to a problem? Please describe.**
* Currently, We are missing the Slack invite link in the read me

**Describe the solution you'd like**
1. Go to the readme file
2. Add the following section towards the end of the read-me file

```
### Join our Slack Community
Join our Slack community to connect with other members, ask questions, and collaborate on projects. [Slack Invite Link](https://join.slack.com/t/tilliopensour-wyp9205/shared_invite/zt-206f4f11s-HoII8Kob45f6WK3GPIIi6g)
```
3. Sent a pull request with the updated change

**Comment by Sanjana0319** [comment]
I would like to work on this
