### ISSUE TITLE
Add the tests action status to the read me 

### ISSUE THREAD

**Issue by anjula-sack** [tillioss/tilli-machine-learning#7]
**Is your feature request related to a problem? Please describe.**
* We need to show the tests status in the readme so we can view it easily

**Describe the solution you'd like**
* Go to the readme file
* Add the following code to the readme
* Create a pull request

`[![CI/CD Test](https://github.com/tillioss/tilli-machine-learning/actions/workflows/test.yml/badge.svg)](https://github.com/tillioss/tilli-machine-learning/actions/workflows/test.yml)`

**Comment by Sanjana0319** [comment]
I would like to work on this.
